### ISSUE TITLE
Problem installing addin

### ISSUE THREAD

**Issue by ti24horas** [monoman/PackageManagerAddin#1]
The github project does not contains instructions in how to install/reference your addin.
I tried to create a new add-in repository (local), but Monodevelop claims that main.rep not found.

There are any instructions in how to achieve addin install?

**Comment by monoman** [comment]
Sorry, this addin project is just an skeleton just now, it would do no good if you could install it. 
I have little time to work on it right now but accept contributions if someone would like to put some flesh on it.

There were news  some time ago that MonoDevelop main devs were already working on a similar plugin but I have not followed up to see if they have prioritized it.
